version: "3"
services:
  house_project:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: house_project
    restart: on-failure
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://property_u:property_p@house_project_postgresql/property_db
      UPLOAD_FOLDER: uploads
      SECRET_KEY: fluidtech2propertymanagement
      APP_SETTINGS: config.StagingConfig
      PROD_SERVER: 167.99.85.35
    ports:
      - "7001:7001"
    volumes:
      - ./:/house_project
    depends_on:
      - house_project_postgresql
  house_project_postgresql:
    image: postgres:alpine
    container_name: house_project_postgresql
    restart: always
    environment:
      POSTGRES_DB: property_db
      POSTGRES_USER: property_u
      POSTGRES_PASSWORD: property_p
    ports:
      - "7309:5432"
    volumes:
      - "/var/www/property_postgres/property:/var/lib/postgresql/data"

